### ISSUE TITLE
For few URLs getting 'PHP Fatal error:  Uncaught Error: Call to a member function uri() on null in'

### ISSUE THREAD

**Issue by rrjanbiah** [gorkalaucirica/RedirectChecker#3]
Complete error:

```
PHP Notice:  Undefined offset: -1 in /mine/redirect-checker/vendor/gorkalaucirica/redirect-checker/src/GorkaLaucirica/RedirectChecker/Infrastructure/RedirectTraceProvider/Guzzle.php on line 66
PHP Fatal error:  Uncaught Error: Call to a member function uri() on null in /mine/redirect-checker/vendor/gorkalaucirica/redirect-checker/src/GorkaLaucirica/RedirectChecker/Infrastructure/RedirectTraceProvider/Guzzle.php:66
Stack trace:
#0 /mine/redirect-checker/vendor/gorkalaucirica/redirect-checker/src/GorkaLaucirica/RedirectChecker/Infrastructure/RedirectTraceProvider/Guzzle.php(37): GorkaLaucirica\RedirectChecker\Infrastructure\RedirectTraceProvider\Guzzle->replaceLastItemsStatusCode(Array, 404)
#1 /mine/redirect-checker/vendor/gorkalaucirica/redirect-checker/src/GorkaLaucirica/RedirectChecker/Application/Query/CheckRedirectionHandler.php(27): GorkaLaucirica\RedirectChecker\Infrastructure\RedirectTraceProvider\Guzzle->getRedirectionTrace(Object(GorkaLaucirica\RedirectChecker\Domain\Redirection))
#2 /mine/redirect-checker/vendor/gorkalaucirica/redirect-checker/src/GorkaLaucirica/RedirectChecker/Infrastructure/Ui/Cli/Symfony/CheckRedirectionFromYaml in /mine/redirect-checker/vendor/gorkalaucirica/redirect-checker/src/GorkaLaucirica/RedirectChecker/Infrastructure/RedirectTraceProvider/Guzzle.php on line 66

```

**Comment by gorkalaucirica** [comment]
Fixed in #4
